#!/bin/bash
sudo apt-get update
sudo apt-get install -y apache2
sudo systemctl start apache2
sudo systemctl enable apache2
echo "<html><body bgcolor=black><center><h1><p><font color=red>Hi GlobalLogic</h1></center></body></html>" > /var/www/html/index.html
sudo systemctl start apache2
sudo systemctl enable apache2
sudo service apache2 restart
