apiVersion : apps/v1
kind: Deployment
metadata:
  name: kub1
  labels:
    app: K8s-App
    env: prod
    owner: mykhailokolodii
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kub
  template:
    metadata:
      labels:
        project: kub
    spec:
      containers:
        - name: kubweb
          image:  muxaylo/my-php-image:latest
          ports:
            - containerPort: 80 



---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: scale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scale
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:    
      name: memory
      target: 
        type: Utilization
        averageUtilization: 80


