
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata: 
  name  : mykhailo-first-cluster
  region: eu-central-1

nodeGroups:
  - name           : worker-nodes-group-1
    instanceType   : t2.medium
    desiredCapacity: 3
     
