apiVersion : apps/v1
kind: Deployment
metadata:
  name  : {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deploy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      labels:
        project: {{ .Release.Name }} # Service will look for these PODS Labels!!
    spec:
      containers:
        - name  : {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          ports:
            - containerPort: 80
